### ISSUE TITLE
Data format in jailbreak device-tree

### ISSUE THREAD

**Issue by oschanger** [freedomtan/iOS-device-tree-dump#1]
When i dumped device-tree info on my jailbreak device.I got something like this:
**memory-frequency Data <0008af2f 00000000>**
I wonder what is this 'Data' format.It's a raw data or memory address.

**Comment by oschanger** [comment]
Some of the raw data seems to be Base64 encoded

**Comment by oschanger** [comment]
Some of the raw data is Base64 encoded

**Comment by freedomtan** [comment]
I have no idea. It seems to me that there is no way to tell/detect the data format of things in device tree nodes. If you know how to do it, please let me know. I'll update code to make data more human readable. For memory-frequency, you probably wanna check https://opensource.apple.com/source/xnu/xnu-4570.1.46/pexpert/arm/pe_identify_machine.c.auto.html

**Comment by oschanger** [comment]
Em..Can i call DTGetProperty() in some way to get the value or other IOKit api.

**Comment by freedomtan** [comment]
I think we are talking about different things. The device tree information my little program examining is what used by boot loader and passed to the XNU kernel. And you are probably talking about what you get from [ioreg](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/ioreg.8.html).  To see how data printed by `ioreg` are formatted, check its [source code](https://github.com/opensource-apple/IOKitTools/blob/master/ioreg.tproj/ioreg.c). Basically, there are all kinds of guesses. And [`DTGetProperty()`](https://github.com/apple/darwin-xnu/blob/master/pexpert/gen/device_tree.c#L365) is kernel function provided by [Platform Expert](http://osxbook.com/book/bonus/ancient/whatismacosx/arch_xnu.html). If you can write kernel modules or something like that, you can call it.
